export interface WorkData {
    heading: string,
    org?: string,
    type?: string,
    startTime?: string,
    endTime?: string,
    isData: boolean,
    brief: string,
    descrition?: string,
    logoURL?: string,
    tools?: string,
}


export const WORK_DATA: WorkData[] = [
    // {
    //     heading: 'Three.js',
    //     type: 'Fun',
    //     isData: false,
    //     startTime: '',
    //     endTime: '',
    //     brief: '',
    //     descrition: '',
    //     logoURL: '',
    // },
    {
        heading: 'Teknofeet Marketplace System',
        org: 'Teknofeet',
        type: 'Work',
        isData: true,
        startTime: 'Nov 2021',
        endTime: 'Present',
        brief: `Teknofeet envissioned itself as a marketplace, enabling brands to leverage their technology to reach to customer base and minimize the returns through online sale.
        <br>I designed the architecture, lead the software team which developed the system enabling the brands to seamlessly integrate with us directly or through Aggregators such as OMS Guru, Uniware, BrownTape, etc`,
        descrition: '',
        tools: 'Angular, NodeJS, Jest, Three.js, Nginx, ExpressJS, MySQL, Docker',
    },
    {
        heading: 'Teknofeet.com',
        org: 'Teknofeet',
        type: 'Work',
        isData: true,
        startTime: 'Nov 2021',
        endTime: 'Present',
        brief: `Teknofeet is first Indian Footcommerce company to talk about fit according to volumental analysis of foot. 
        Teknofeet uses CV and ML to accurately generate a 3-D feet model and then recommends shoe after matching feet dimensions with footwear inner dimensions.
        <br><br>As the core member of Software Team at Teknofeet, I laid the foundation of <a href='https://teknofeet.com/'>www.teknofeet.com</a> `,
        descrition: '',
        logoURL: '',
        tools: 'Angular, NodeJS, Three.js, Nginx, ExpressJS, MySQL, Docker',
    },
    {
        heading: 'Warehouse Management System',
        org: 'Addverb',
        type: 'Work',
        isData: true,
        startTime: 'Jun 2021',
        endTime: 'Oct 2021',
        brief: '',
        descrition: '',
        logoURL: '',
        tools: 'Angular, Spring, Kafka, SQL, Docker',
    },
    {
        heading: 'SSO',
        org: 'Addverb',
        type: 'Internship',
        isData: true,
        startTime: 'Aug 2020',
        endTime: 'Jan 2021',
        brief: '',
        descrition: '',
        logoURL: '',
        tools: 'Angular, Spring, Kafka, SQL, Docker',
    },
]