export interface WorkData {
    heading: string,
    org?: string,
    type?: string,
    startTime?: string,
    endTime?: string,
    isData: boolean,
    brief: string,
    descrition?: string,
    logoURL?: string,
}


export const WORK_DATA: WorkData[] = [
    // {
    //     heading: 'Three.js',
    //     type: 'Fun',
    //     isData: false,
    //     startTime: '',
    //     endTime: '',
    //     brief: '',
    //     descrition: '',
    //     logoURL: '',
    // },
    {
        heading: 'Teknofeet.com',
        org: 'Teknofeet',
        type: 'Work',
        isData: true,
        startTime: 'Nov 2021',
        endTime: 'Present',
        brief: '',
        descrition: '',
        logoURL: '',
    },
    {
        heading: 'Teknofeet Marketplace System',
        org: 'Teknofeet',
        type: 'Work',
        isData: true,
        startTime: 'Nov 2021',
        endTime: 'Present',
        brief: '',
        descrition: '',
        logoURL: '',
    },
    {
        heading: 'Warehouse Management System',
        org: 'Addverb',
        type: 'Work',
        isData: true,
        startTime: 'Jun 2021',
        endTime: 'Oct 2021',
        brief: '',
        descrition: '',
        logoURL: '',
    },
    {
        heading: 'SSO',
        org: 'Addverb',
        type: 'Internship',
        isData: true,
        startTime: 'Aug 2020',
        endTime: 'Jan 2021',
        brief: '',
        descrition: '',
        logoURL: '',
    },
]